name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: patrick-kidger/action_update_python_project@v1
        with:
            python-version: "3.11"
            test-script: |
                cp -r ${{ github.workspace }}/test ./test
                cp ${{ github.workspace }}/pyproject.toml ./pyproject.toml
                python -m pip install -r ./test/requirements.txt
                pytest ./test
            pypi-token: ${{ secrets.pypi_token }}
            github-user: thibmonsel
            github-token: ${{ github.token }} 